---
controller_credentials:
- name: ZXplore 
  description: Credential to Login to the IBM ZXplore Public Mainframe
  organization: "{{ my_org }}"
  credential_type: Machine
  inputs:
    username: "{{ zos_username }}"
    password: "{{ zos_password }}"

- name: SNOW - C. Norville 
  description: C. Norville Credentials to SNOW TPP Instance ven07621
  organization: "{{ my_org }}"
  credential_type: ServiceNow ITSM Credential
  inputs:
    instance: "{{ snow_instance }}"
    username: "{{ snow_username }}"
    password: "{{ snow_password }}"
