---
eda_credentials:
  - name: EDA Webhook Cred for Event Streams 
    description: Basic EDA Webhook
    credential_type: 'Basic Event Stream'
    organization: "Default"
    inputs:
      password: "{{ my_aap_password }}"
      username: "cnorville"
